apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  type: LoadBalancer
  selector:
    app: myservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30945